### ISSUE TITLE
GET POST DELETE以外の場合が実行された時にstatusがunknown

### ISSUE THREAD

**Issue by libknt** [libknt/webserv#128]

**Comment by massahito** [comment]
curl -X HOGE http://localhost
とかやるとstatus codeが未定義値で帰ってきて、statusがUNKNOWNになっている。

**Comment by soooku** [comment]
これでallow_methodの問題と一緒に修正しました。
https://github.com/libknt/webserv/pull/135

**Comment by massahito** [comment]
ありがとうございます。
