### ISSUE TITLE
siege -b をした時に Availabilityが99.5%未満になる

### ISSUE THREAD

**Issue by soooku** [libknt/webserv#95]
- 荒井のPCで動かしたらほぼ100%になる
- 校舎macで動かした場合は94%弱になる
- しばらく経つと `socket: unable to connect sock.c:282: Connection refused` というメッセージが表示される
- 参考 評価項目: Availability should be above 99.5% for a simple GET on an empty page with a siege -b on that page.

**Comment by massahito** [comment]
usleep挟んだらいけた。

**Comment by massahito** [comment]
siegeの実装のせいなのでclose
